### ISSUE TITLE
Docker::face_detect.py: error == cudaSuccess (8 vs. 0)  invalid device function

### ISSUE THREAD

**Issue by zehuanw** [scanner-research/scanner#75]
Dear Colleagues,

I'm new to scanner and trying to run some caffe related samples in nvidia-docker as suggested in https://github.com/scanner-research/scanner#quick-start
and then run the face_detect.py with 
#python examples/face_detection/face_detect.py
I encountered an error while caffe forwarding (just after network parsing) as below.
I tried with some simple simple cuda programs and the examples in tutorial, they can run well on my platform. 

I don't know if I made any mistake or such whether error can be repro on your side. 
Any suggestions will be appreciate.
>> BTW. when I run with pose_detect.py there are also some errors like scannerpy.common.ScannerException: Op CPM2Input does not exist

I0609 09:18:21.615213   162 net.cpp:200] res2a_res2a_relu_0_split does not need backward computation.
I0609 09:18:21.615218   162 net.cpp:200] res2a_relu does not need backward computation.
I0609 09:18:21.615221   162 net.cpp:200] res2a does not need backward computation.
I0609 09:18:21.615226   162 net.cpp:200] res2a_branch2c does not need backward computation.
I0609 09:18:21.615231   162 net.cpp:200] res2a_branch2b_relu does not need backward computation.
I0609 09:18:21.615236   162 net.cpp:200] res2a_branch2b does not need backward computation.
I0609 09:18:21.615239   162 net.cpp:200] res2a_branch2a_relu does not need backward computation.
I0609 09:18:21.615244   162 net.cpp:200] res2a_branch2a does not need backward computation.
I0609 09:18:21.615248   162 net.cpp:200] res2a_branch1 does not need backward computation.
I0609 09:18:21.615253   162 net.cpp:200] pool1_pool1_0_split does not need backward computation.
I0609 09:18:21.615257   162 net.cpp:200] pool1 does not need backward computation.
I0609 09:18:21.615262   162 net.cpp:200] conv1_relu does not need backward computation.
I0609 09:18:21.615267   162 net.cpp:200] conv1 does not need backward computation.
I0609 09:18:21.615270   162 net.cpp:200] input does not need backward computation.
I0609 09:18:21.615274   162 net.cpp:242] This network produces output score_cls
I0609 09:18:21.615280   162 net.cpp:242] This network produces output score_reg
I0609 09:18:21.615376   162 net.cpp:255] Network initialization done.
W0609 09:18:21.683058   158 net.hpp:41] DEPRECATED: ForwardPrefilled() will be removed in a future version. Use Forward().
**F0609 09:18:21.733853   162 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function**

**Comment by apoms** [comment]
Hi Zehuan,

I just pulled a fresh version of the docker files and was able to run

```
bash nets/get_caffe_facenet.sh
python examples/face_detection/face_detect.py
```

successfully. What GPU are you using and what driver + CUDA version are you using? We've noticed some issues with Caffe in the past depending on those.

For your other issue, the pose detection script depends on the CPM network (https://github.com/CMU-Perceptual-Computing-Lab/openpose) which used to require building Scanner against their custom version of Caffe (so the CPM2 ops were not built by default). This has recently changed and their network can work with a default Caffe version but we haven't updated our implementation to work with their new network yet. For now, you can build their previous version of caffe (https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose) and link Scanner against that using the `Caffe_DIR=/path/to/caffe/install` environment variable when building Scanner along with enabling the CPM2 ops with `-DBUILD_CPM2=ON`. 

Thanks,

Alex

**Comment by zehuanw** [comment]
Hi Apoms,

Sorry for late reply. I have setup a new desktop for test last week.
I found that when I remove my K20 in my desktop this issue is solved. 
My another GPU card in my desktop is TITANX (Pascal SM61)
Now I can run face_detection as expected!

When I'm browsing the dockerfile: https://github.com/scanner-research/scanner-docker/blob/master/ubuntu16.04/Dockerfile

I found that in the dockerfile Caffe is only built with SM61. 
It looks like the problem.

**Comment by apoms** [comment]
Nice catch; that's definitely the issue. We should be building Caffe for all all versions instead of just sm61.

Thanks! Will have that fixed shortly. I filed an issue to track here: https://github.com/scanner-research/scanner-docker/issues/1

**Comment by willcrichton** [comment]
FWIW @mattperron has this problem too so we can replicate on his setup as well.
